
const MAD_LIB = getLongMadLib(); // You can try using both getShortMadLib() and getLongMadLib()

const REGEX = {
    word: /^[A-Za-z]+$/,
    properNoun: /^[A-Z][A-Za-z]*$/,
    adjective: /^[A-Za-z]*[yY]$/,
    quote: /^(['"])(.+)\1$/
};

/**
 * This function is done for you.
 * This function is called when the page is initially loaded.
 * It will generate inputs based on the contents of the MAD_LIB.fillers list.
 * Each input has an associated label and error text that begins as empty.
 */
function setup() {
    let parentNode = document.getElementById("madlib-questions");

    for(let i = 0; i < MAD_LIB.fillers.length; i++) {
        let currLib = MAD_LIB.fillers[i];

        let newDivNode = document.createElement("div");
        newDivNode.className = "mb-2"

        let newInputNode = document.createElement("input");
        newInputNode.id = currLib.id + "-input";
        newInputNode.style.maxWidth = "25em";
        newInputNode.className = "form-control"
        newInputNode.placeholder = currLib.exampleText;
        
        let newLabelNode = document.createElement("label");
        newLabelNode.htmlFor = currLib.id + "-input";
        newLabelNode.innerText = currLib.friendlyText;

        let newErrorTextNode = document.createElement("p");
        newErrorTextNode.id = currLib.id + "-error-text";
        newErrorTextNode.style.color = "red";
        newErrorTextNode.innerText = "";

        newDivNode.appendChild(newLabelNode);
        newDivNode.append(newInputNode);
        newDivNode.append(newErrorTextNode);

        parentNode.appendChild(newDivNode);
    }
}

/**
 * This function is done for you.
 * This function is called anytime the user presses the "Generate!" button.
 * It first checks if the given inputs are valid. If they are valid,
 * the madlib is generated by calling the generateLib function.
 */
function generate() {
    if (validate()) {
        generateLib();
        alert("Success! Please see below for your MadLib :)");
    } else {
        alert("Uh oh, please check your form submission.")
    }
}

/**
 * This function is called by generate any time the user requests
 * generation and validation passes. Generate the `madlib-result` div
 * such that any existing HTML is replaced with the newest madlib contents.
 */
function generateLib() {
    const resultDiv = document.getElementById("madlib-result");
    resultDiv.innerHTML = "";

    let pBuilder = document.createElement("p"); 

    MAD_LIB.text.forEach(segment => {
        if (segment.segmentType === "static") {
            pBuilder.innerText += segment.text;
        }
        else if (segment.segmentType === "fillable") {
            let inputEl = document.getElementById(segment.id + "-input");
            pBuilder.innerText += inputEl.value;
        }
        else if (segment.segmentType === "newline") {
            resultDiv.appendChild(pBuilder);
            pBuilder = document.createElement("p");
        }
    });

    resultDiv.appendChild(pBuilder);
}

/**
 * This function should check if any of the inputs have validation errors.
 * For each input, if it has validation errors, set the appropriate error text.
 * Otherwise, reset any error text that may exist. Use error text appropriate to
 * each form control, for exdample if validation fails on a quote, the error text
 * should say 'Please type 1 or more characters between quotes.' If the validation fails 
 * on a word, the error text should say 'Please type 1 or more letters, without spaces.'
 * 
 * Be sure to return true or false! Return true if all inputs are valid,
 * otherwise return false if ANY input is invalid.
 * 
 * @returns {boolean} true if form is valid, false otherwise.
 */
function validate() {
    let isValid = true;
    
    // TODO: If any inputs are invalid, set their error text.
    //       After checking ALL inputs, return true/false if
    //       the entire form was valid or not.

    //_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-

    for(let i = 0; i < MAD_LIB.fillers.length; i++) {


        let currLib = MAD_LIB.fillers[i];
        let currInputId = currLib.id + "-input";
        let currErrorTextId = currLib.id + "-error-text";

        let currInput = document.getElementById(currInputId);
        let currErrorText = document.getElementById(currErrorTextId);
        let value = currInput.value.trim();

        let valid = REGEX[currLib.type].test(value);

        // Set the proper error messages
        if (!valid) {
            currInput.classList.add("is-invalid");
            isValid = false;

            if (currLib.type === "word") {
                currErrorText.innerText = "Please type 1 or more letters, without spaces or special characters.";
            } else if (currLib.type === "properNoun") {
                currErrorText.innerText = "Please type 1 or more letters, without special characters, starting with a capital letter.";
            } else if (currLib.type === "adjective") {
                currErrorText.innerText = "Please type 1 or more letters, without special characters, ending with a y.";
            } else if (currLib.type === "quote") {
                currErrorText.innerText = "Please type 1 or more characters between single or double quotes.";
            }

        } else {
            currInput.classList.remove("is-invalid");
            currErrorText.innerText = "";
        }     
    }

    return isValid;
}

// Don't remove this! It runs the setup function on page load.
window.onload = setup;